type Product = {
  id: number,
  text: string,
  Description: string,
  category: string[],
  image: string,
  imgsmolde: string,
};

export const products: Product[] = [
  //Lista de Buzos
  {
    id: 1,
    text: "BUZO TIAGO",
    Description: "Buzo de friza invisible liso – capucha forrada y puños al tono- Bordado – OPCIONAL manga estampada",
    category: ["buzos"],
    image: "/Clothes/buzo/buzo_TIAGO.jpeg",
    imgsmolde: "/Clothes/buzo/molde_TIAGO.png",
  },
  {
    id: 2,
    text: "BUZO POLO",
    Description: "Buzo friza invisible a 3 colores, combinado en mangas recortes horizontales y en capucha - Bordado. Capucha forrada y puños a tono.",
    category: ["buzos"],
    image: "/Clothes/buzo/buzo_Polo.jpeg",
    imgsmolde: "/Clothes/buzo/molde_POLO.png",
  },
  {
    id: 3,
    text: "BUZO ALMA",
    Description: "Buzo friza invisible a 3 colores, combinado en mangas recortes verticales - Bordado. Capucha forrada y puños a tono.",
    category: ["buzos"],
    image: "/Clothes/buzo/buzo_ALMA.jpeg",
    imgsmolde: "/Clothes/buzo/molde_ALMA.png",
  },
  {
    id: 4,
    text: "BUZO ANGIE",
    Description: "Buzo friza invisible a 3 colores, combinado en bolsillo canguro y con cintas aplicadas - Bordado. Capucha forrada y puños a tono. OPCIONAL manga estampada.",
    category: ["buzos"],
    image: "/Clothes/buzo/buzo_ANGIE.jpeg",
    imgsmolde: "/Clothes/buzo/molde_ANGIE.png",
  },
  {
    id: 5,
    text: "BUZO BENI",
    Description: "Buzo friza invisible a 3 colores, combinado en bolsillo canguro y con cintas aplicadas - Bordado. Capucha forrada y puños a tono. OPCIONAL manga estampada.",
    category: ["buzos"],
    image: "/Clothes/buzo/buzo_BENI.jpeg",
    imgsmolde: "/Clothes/buzo/molde_BENI.png",
  },
  {
    id: 6,
    text: "BUZO AILU",
    Description: "Buzo friza invisible a 3 colores, combinado en bolsillo canguro y con cintas aplicadas - Bordado. Capucha forrada y puños a tono. OPCIONAL manga estampada.",
    category: ["buzos"],
    image: "/Clothes/buzo/buzo_AILU.jpeg",
    imgsmolde: "/Clothes/buzo/molde_AILU.png",
  },
  {
    id: 7,
    text: "BUZO MARTU",
    Description: "Buzo friza invisible a 3 colores, combinado en mangas recortes horizontales, verticales y en capucha – Bordado y estampado. Capucha forrada y puños a tono. Manga Raglan.",
    category: ["buzos"],
    image: "/Clothes/buzo/buzo_MARTU.jpeg",
    imgsmolde: "/Clothes/buzo/molde_MARTU.png",
  },
  {
    id: 8,
    text: "BUZO PILI",
    Description: "Buzo friza invisible a 2 colores, combinado en mangas recortes horizontales y en cuerpo recortes verticales - Bordado. Capucha forrada y puños a tono.",
    category: ["buzos"],
    image: "/Clothes/buzo/buzo_PILI.jpeg",
    imgsmolde: "/Clothes/buzo/molde_PILI.png",
  },
  {
    id: 9,
    text: "BUZO ZOE",
    Description: "Buzo friza invisible a 3 colores, combinado en mangas y cuerpo con recortes verticales - Bordado. Capucha forrada y puños a tono.",
    category: ["buzos"],
    image: "/Clothes/buzo/buzo_ZOE.jpeg",
    imgsmolde: "/Clothes/buzo/molde_ZOE.png",
  },

  //Lista de Camperas
  {
    id: 10,
    text: "CAMPERA CATA",
    Description: "Campera con cierre de friza invisible a un color - Bordada. Capucha forrada y puños combinados. OPCIONAL: mangas estampadas",
    category: ["camperas"],
    image: "/Clothes/campera/CATA.jpeg",
    imgsmolde: "/Clothes/campera/molde_CATA.png",
  },
  {
    id: 11,
    text: "CAMPERA JAZ",
    Description: "Campera con cierre de friza invisible a un color, recorrido de cintas – Bordada. Capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/JAZ.jpeg",
    imgsmolde: "/Clothes/campera/molde_LARA.png",
  },
  {
    id: 12,
    text: "CAMPERA AGUS",
    Description: "Campera con cierre de friza invisible a 3 colores con recortes en mangas – Bordada. Capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/AGUS.jpeg",
    imgsmolde: "/Clothes/campera/molde_AGUS.png",
  },
  {
    id: 13,
    text: "CAMPERA ALEJO",
    Description: "Campera con cierre de friza invisible a 2 colores combinada - Bordada. Capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/ALEJO.jpeg",
    imgsmolde: "/Clothes/campera/molde_ALEJO.png",
  },
  {
    id: 14,
    text: "CAMPERA BAUTI",
    Description: "Campera con broches de friza invisible combinada a 2 colores – estilo universitario - Bordada. Capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/BAUTI.jpeg",
    imgsmolde: "/Clothes/campera/molde_BAUTI.png",
  },
  {
    id: 15,
    text: "CAMPERA LAUTI",
    Description: "Campera con broches de friza invisible combinada a 2 colores – estilo universitario - Bordada. Cuello y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/LAUTI.jpeg",
    imgsmolde: "/Clothes/campera/molde_LAUTI.png",
  },
  {
    id: 16,
    text: "CAMPERA JOACO",
    Description: "Campera con broches de friza invisible combinada a 2 colores – estilo universitario - Bordada. Cuello y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/JOACO.jpeg",
    imgsmolde: "/Clothes/campera/molde_JOACO.png",
  },
  {
    id: 17,
    text: "CAMPERA DENU ",
    Description: "Campera con broches de friza invisible combinada a 2 colores – estilo universitario - Bordada. Cuello y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/DENU.jpeg",
    imgsmolde: "/Clothes/campera/molde_DENU.png",
  },
  {
    id: 18,
    text: "CAMPERA LULU ",
    Description: "Campera con cierre de Ketten combinada a 2 colores con recorte horizontal. Estilo automovilismo Bordada. Cuello y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/LULU.jpeg",
    imgsmolde: "/Clothes/campera/molde_LULU.png",
  },
  {
    id: 19,
    text: "CAMPERA CRIS ",
    Description: "Campera con cierre de friza invisible combinada a 3 colores con recortes en pico – Bordada. Capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/CRIS.jpeg",
    imgsmolde: "/Clothes/campera/molde_CRIS.png",
  },
  {
    id: 20,
    text: "CAMPERA RAMI ",
    Description: "Campera con cierre de friza invisible combinada a 2 colores- con cinta aplicada– Bordada. Capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/RAMI.jpeg",
    imgsmolde: "/Clothes/campera/molde_RAMI.png",
  },
  {
    id: 21,
    text: "CAMPERA BIAN ",
    Description: "Campera con cierre de friza invisible combinada a 3 colores con recortes en diagonal, asimétrica – Bordada. Capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/BIAN.jpeg",
    imgsmolde: "/Clothes/campera/molde_BIAN.png",
  },
  {
    id: 22,
    text: "CAMPERA VAL ",
    Description: "Campera con cierre de friza invisible combinada a 3 colores – recortes en triangulo– Bordada. Capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/VAL.jpeg",
    imgsmolde: "/Clothes/campera/molde_VAL.png",
  },
  {
    id: 23,
    text: "CAMPERA MATE ",
    Description: "Campera con cierre de friza invisible combinada a 3 colores con cortes horizontales– Bordada. Capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/MATE.jpeg",
    imgsmolde: "/Clothes/campera/molde_MATE.png",
  },
  {
    id: 24,
    text: "CAMPERA SANTI ",
    Description: "Campera con cierre de friza invisible combinada a 2 colores con recorte ver􀆟cal. OPCIONALES cintas aplicadas – Bordada. Capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/SANTI.jpeg",
    imgsmolde: "/Clothes/campera/molde_SANTI.png",
  },
  {
    id: 25,
    text: "CAMPERA IARU ",
    Description: "Campera con cierre de friza invisible combinada a 3 colores en pico – Bordada. Capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/IARU.jpeg",
    imgsmolde: "/Clothes/campera/molde_IARU.png",
  },
  {
    id: 26,
    text: "CAMPERA BRI ",
    Description: "Campera con cierre de friza invisible combinada a 3 colores con recortes de pico hacia arriba. Bordada – Con capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/BRI.jpeg",
    imgsmolde: "/Clothes/campera/molde_BRI.png",
  },
  {
    id: 27,
    text: "CAMPERA MORE ",
    Description: "Campera con cierre de friza invisible combinada a 3 colores con recortes en pico. Bordada -Con capucha forrada y puños combinados.",
    category: ["camperas"],
    image: "/Clothes/campera/MORE.jpeg",
    imgsmolde: "/Clothes/campera/molde_MORE.png",
  },
  // lISTA REMERAS
  {
    id: 28,
    text: "REMERA THEO ",
    Description: "Remera jersey 24/1 a un color – Bordada. Cuello a tono.",
    category: ["remeras"],
    image: "/Clothes/remeras/THEO.jpeg",
    imgsmolde: "/Clothes/remeras/molde_THEO.png",
  },
  {
    id: 29,
    text: "REMERA ALDI ",
    Description: "Remera jersey 24/1 a un color – Bordada. Cuello y puños COMBINADOS.",
    category: ["remeras"],
    image: "/Clothes/remeras/ALDI.jpeg",
    imgsmolde: "/Clothes/remeras/molde_ALDI.png",
  },
  {
    id: 30,
    text: "REMERA URI ",
    Description: "Remera jersey 24/1 combinada a 2 colores – Bordada. Cuello a tono.",
    category: ["remeras"],
    image: "/Clothes/remeras/URI.jpeg",
    imgsmolde: "/Clothes/remeras/molde_URI.png",
  },
  {
    id: 31,
    text: "REMERA JUAMPA ",
    Description: "Remera jersey 24/1 a un color – Bordada. Cuello a tono. Cinta aplicada en mangas.",
    category: ["remeras"],
    image: "/Clothes/remeras/JUAMPA.jpeg",
    imgsmolde: "/Clothes/remeras/molde_JUAMPA.png",
  },
  {
    id: 32,
    text: "REMERA MARCO ",
    Description: "Remera jersey 24/1 combinada con recortes en mangas – Bordada. Cuello y puños a tono.",
    category: ["remeras"],
    image: "/Clothes/remeras/MARCO.jpeg",
    imgsmolde: "/Clothes/remeras/molde_MARCO.png",
  },
  {
    id: 33,
    text: "REMERA NERE",
    Description: "Remera jersey 24/1 a 2 colores combinada – Manga Raglan – Bordada. Cuello a tono.",
    category: ["remeras"],
    image: "/Clothes/remeras/NERE.jpeg",
    imgsmolde: "/Clothes/remeras/molde_NERE.png",
  },
  {
    id: 34,
    text: "REMERA NICKI",
    Description: "Remera jersey 24/1 combinada 2 colores con recorte horizontal y 􀆟ras – Bordada. Cuello y puños a tono.",
    category: ["remeras"],
    image: "/Clothes/remeras/NICKI.jpeg",
    imgsmolde: "/Clothes/remeras/molde_NICKI.png",
  },

  // Lista Chombas
  {
    id: 35,
    text: "CHOMBA ABRU",
    Description: "Chomba piquet a 2 colores con corte ver􀆟cal y mangas a tono – Bordada. Cuello y puños combinados.",
    category: ["chombas"],
    image: "/Clothes/chombas/ABRU.jpeg",
    imgsmolde: "/Clothes/chombas/molde_ABRU.png",
  },
  {
    id: 36,
    text: "CHOMBA BENJA",
    Description: "Chomba piquet a 2 colores – combinada con cinta aplicada– Bordada. Cuello y puños combinados.",
    category: ["chombas"],
    image: "/Clothes/chombas/BENJA.jpeg",
    imgsmolde: "/Clothes/chombas/molde_BENJA.png",
  },
  {
    id: 38,
    text: "CHOMBA FRAN",
    Description: "Chomba piquet 3 colores con recortes horizontales – Bordada. Cuello y puños combinados.",
    category: ["chombas"],
    image: "/Clothes/chombas/FRAN.jpeg",
    imgsmolde: "/Clothes/chombas/molde_FRAN.png",
  },
  {
    id: 40,
    text: "CHOMBA JUANI",
    Description: "Chomba piquet a un 2 colores- combinada– Bordada. Cuello y puños combinados.",
    category: ["chombas"],
    image: "/Clothes/chombas/JUANI.jpeg",
    imgsmolde: "/Clothes/chombas/molde_JUANI.png",
  },
  {
    id: 41,
    text: "CHOMBA JULI",
    Description: "Chomba piquet a 3 colores con corte en pico – Bordada. Cuello y puños combinados.",
    category: ["chombas"],
    image: "/Clothes/chombas/JULI.jpeg",
    imgsmolde: "/Clothes/chombas/molde_JULI.png",
  },
  {
    id: 42,
    text: "CHOMBA MARU",
    Description: "Chomba piquet a 3 colores – combinada con picos y triangulos– Bordada. Cuello y puños combinados.",
    category: ["chombas"],
    image: "/Clothes/chombas/MARU.jpeg",
    imgsmolde: "/Clothes/chombas/molde_MARU.png",
  },
  {
    id: 43,
    text: "CHOMBA MELU",
    Description: "Chomba piquet a 3 colores con recortes horizontales – Bordada. Cuello y puños combinados.",
    category: ["chombas"],
    image: "/Clothes/chombas/MELU.jpeg",
    imgsmolde: "/Clothes/chombas/molde_MELU.png",
  },
  {
    id: 44,
    text: "CHOMBA NAHU",
    Description: "Chomba piquet a 3 colores con corte recto en largo – Bordada. Cuello y puños combinados.",
    category: ["chombas"],
    image: "/Clothes/chombas/NAHU.jpeg",
    imgsmolde: "/Clothes/chombas/molde_NAHU.png",
  },
  {
    id: 45,
    text: "CHOMBA SOFI",
    Description: "Chomba piquet a 3 colores con recortes horizontales – Bordada. Cuello y puños combinados..",
    category: ["chombas"],
    image: "/Clothes/chombas/SOFI.jpeg",
    imgsmolde: "/Clothes/chombas/molde_SOFI.png",
  },
  {
    id: 46,
    text: "CHOMBA TATI",
    Description: "Chomba de piqué 20/1 a 2 colores combinada con recortes horizontales – Bordada. Cuello y puños a tono.",
    category: ["chombas"],
    image: "/Clothes/chombas/TATI.jpeg",
    imgsmolde: "/Clothes/chombas/molde_TATI.png",
  },
  {
    id: 47,
    text: "CHOMBA TIZI",
    Description: "Chomba piquet 3 colores con recortes horizontales en pico – Bordada. Cuello y puños combinados.",
    category: ["chombas"],
    image: "/Clothes/chombas/TIZI.jpeg",
    imgsmolde: "/Clothes/chombas/molde_TIZI.png",
  },
  {
    id: 48,
    text: "CHOMBA TOMI",
    Description: "Chomba piquet a 3 colores con corte Diagonal – Bordada. Cuello y puños combinados.",
    category: ["chombas"],
    image: "/Clothes/chombas/TOMI.jpeg",
    imgsmolde: "/Clothes/chombas/molde_TOMI.png",
  },
  {
    id: 49,
    text: "CHOMBA VALEN",
    Description: "Chomba piquet a un color – Bordada. Cuello y puños combinados.",
    category: ["chombas"],
    image: "/Clothes/chombas/VALEN.jpeg",
    imgsmolde: "/Clothes/chombas/molde_VALEN.png",
  },
]